language: go
go:
    - 1.13.x
    - 1.14.x
    - 1.15.x
    - 1.16.x
    - 1.17.x
    - 1.18.x
    - 1.19.x
    - master

install:
    - go get -v golang.org/x/tools/cmd/cover
script:
    - go test -v -tags=testcgo -covermode=count -coverprofile=profile.cov
after_success:
    - go get -v github.com/mattn/goveralls
    - export PATH=$PATH:$HOME/gopath/bin
    - goveralls -coverprofile=profile.cov -service=travis-ci
